import { useMemo } from "react";
import { Equal, Expect } from "../helpers/type-utils";

export const Component = () => {
  // useMemo infers pretty good the type from returned value, so no need to type useMemo. But if type is needed it can be done in this way (for properties check error)
  const autoGeneratedIds = useMemo((): string[] => {
    // generate 100 random string uuid's
    return Array.from({ length: 100 }, () =>
      Math.random().toString(36).substr(2, 9)
    );
  }, []);

  type test = Expect<Equal<typeof autoGeneratedIds, string[]>>;
};
